import Link from "next/link";

const sections = [
  ["1. Marketplace role", "MyBlueTrade Network provides technology that helps businesses and independent service providers discover and coordinate work. Unless a written agreement says otherwise, MyBlueTrade is not the hiring business, employer, general contractor, or provider of the underlying trade service."],
  ["2. Independent participation", "Providers decide whether to accept an opportunity and are responsible for their own business registrations, taxes, insurance, tools, transportation, and legally required licenses. A qualification shown in the Network describes demonstrated capability; it does not replace a government license, permit, union classification, or site-specific authorization."],
  ["3. Job scope and payment", "Before accepting work, participants should review the scope, location, schedule, compensation, required tools, supervision, insurance, and cancellation terms supplied for that opportunity. The hiring business remains responsible for lawful classification and timely payment under its agreement with the provider."],
  ["4. Safety and incidents", "Participants must follow applicable law, manufacturer instructions, site rules, and required safety practices. Dangerous conditions, injuries, property damage, harassment, or suspected fraud must be reported promptly to the hiring business and through the Network’s designated support channel. Emergency services should be contacted first when appropriate."],
  ["5. Screening and qualifications", "Identity, credentials, references, assessments, and capability signals may be reviewed, but no screening process eliminates all risk. Hiring businesses must make their own suitability decisions, verify licenses where required, provide competent supervision, and confirm that each worker is authorized for the assigned task."],
  ["6. Insurance and responsibility", "Each participant is responsible for maintaining insurance required by law or the opportunity terms. Responsibility for loss, damage, injury, delay, defective work, and third-party claims follows the parties’ agreement and applicable law. MyBlueTrade does not insure a participant merely by listing or matching an opportunity."],
  ["7. Conduct and platform integrity", "Participants may not misrepresent skills, credentials, availability, identity, work performed, or payment status; circumvent safety controls; discriminate unlawfully; retaliate against a report; or use the Network for illegal activity. Access may be limited while a safety, fraud, payment, or qualification issue is reviewed."],
  ["8. Disputes and legal terms", "Job disputes should first be raised through the documented support process. Any limits of liability, warranty disclaimers, arbitration terms, class-action waiver, governing law, and venue must appear in the final agreement presented at account creation or job acceptance and may vary by jurisdiction."],
];

export const metadata = { title: "Network Terms | MyBlueTrade" };

export default function NetworkTerms() {
  return <main className="min-h-screen bg-bg text-ink"><div className="mx-auto max-w-3xl px-5 py-16 sm:px-8 sm:py-24"><Link href="/network" className="eyebrow text-accent">← MyBlueTrade Network</Link><p className="eyebrow mt-16 text-mut">Working principles · Draft</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.05em] sm:text-6xl">Network Terms</h1><div className="mt-6 rounded-card border border-amber-500/30 bg-amber-100/50 p-4 text-sm leading-6 text-amber-950 dark:bg-amber-300/10 dark:text-amber-100"><strong>Legal review required.</strong> This public summary describes the intended operating model and is not a substitute for jurisdiction-specific marketplace, contractor-classification, insurance, privacy, or dispute-resolution terms prepared by counsel.</div><div className="mt-14 divide-y divide-border">{sections.map(([title, body]) => <section key={title} className="py-8"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-mut">{body}</p></section>)}</div><p className="mt-10 text-xs text-faint">Last updated August 16, 2026 · Draft for product review</p></div></main>;
}
